In [65]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_csv("train.csv",header=None)

In [67]:
df.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121
0,69769,-946,0.1613,0.7960,Panl,N,Bus2,0.0742,0,2,0.2281,0.0650,0.0,180000.0,No,0,Unad,0.0740,0.0,0,0,0.2227,0.3750,0,0,0.289573,0,0.0,0,0,Come,Hout,0.2248,1,0.0,0.0,0.2322,2,0.32,0.3333,13189.5,10,1,0.0,Labs,1.0,0,N,0.2759,0.2377,0,0.32,0,0.008230,0.0665,0,0.0,90000.0,0.622922,0.1613,0.1983,0.3750,0,-6378.0,1,0,227520.0,Hign,0.0,F,-12298,0,0.0,2,0.2759,0,0,0.1816,0.2759,0.0661,0.9851,0,0.8040,0.0,0.3333,0.0,0.384582,0.2269,0.0736,0.2197,0.0,0.0,0.7987,WEDY,0,0.1673,0.3222,0,0,4.0,0,0.3750,NaN,Cass,1,0,0,blos,0,0.9851,regt,0.1847,1.0,-4670,0.9851,0.0,0,Mard,0.0,0.3333,0,0
1,236977,-92,NaN,NaN,NaN,Y,Othr,NaN,0,3,NaN,NaN,NaN,135000.0,NaN,0,Unad,NaN,NaN,0,0,NaN,NaN,0,0,0.514261,0,2.0,0,0,Come,Hout,NaN,1,NaN,2.0,NaN,3,NaN,NaN,13095.0,13,1,NaN,Dris,NaN,0,Y,NaN,NaN,1,NaN,0,0.003069,NaN,0,NaN,90000.0,NaN,NaN,NaN,NaN,0,-1292.0,1,0,161730.0,Secl,NaN,M,-15375,1,0.0,0,NaN,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,-509.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TUEY,0,NaN,NaN,0,0,2.0,0,NaN,23.0,Cass,1,0,0,NaN,0,NaN,NaN,NaN,NaN,-1994,NaN,NaN,0,Mard,0.0,NaN,0,0
2,168821,-1646,0.1124,0.8504,Panl,N,Bus3,0.0387,0,2,0.1614,0.3064,0.0,553500.0,No,0,Spor,0.0386,0.0,0,1,0.1485,0.4167,0,0,0.486906,0,1.0,0,0,Worg,Hout,0.1499,1,0.0,1.0,0.1643,3,0.16,0.3750,26307.0,5,1,0.0,Labs,0.0,0,Y,0.1379,0.1681,0,0.16,0,0.020713,0.3133,0,0.0,135000.0,0.598926,0.1124,0.1322,0.4167,0,-7951.0,1,0,728847.0,Secl,0.0,M,-19307,0,0.0,0,0.1379,0,0,0.1210,0.1379,0.3117,0.9891,0,0.8563,2.0,0.3750,-1474.0,NaN,0.1513,0.0383,0.1269,0.0,0.0,0.8524,TUEY,0,0.1166,0.1611,0,0,1.0,0,0.4167,NaN,Cass,1,0,0,blos,0,0.9891,regt,0.1231,2.0,-2842,0.9891,0.0,0,Sind,0.0,0.3750,0,1
3,94708,-1651,0.0263,NaN,Blok,N,Bus3,NaN,0,2,0.0083,0.0151,0.0,391500.0,No,0,Unad,NaN,NaN,0,1,0.0082,NaN,0,0,0.675705,0,2.0,0,0,Come,Hout,0.0083,1,0.0,2.0,0.0084,2,0.00,0.0417,34636.5,10,1,NaN,Labs,0.0,0,N,0.0345,0.0086,0,0.00,0,0.011703,0.0155,0,NaN,135000.0,0.454321,0.0263,NaN,NaN,0,-1033.0,1,0,474183.0,Secl,0.0,M,-17791,0,0.0,0,0.0345,0,0,NaN,0.0345,0.0154,0.9682,0,NaN,0.0,0.0417,-2016.0,NaN,0.0084,NaN,0.0065,0.0,0.0,NaN,TUEY,0,0.0273,0.0000,0,0,1.0,0,NaN,NaN,Cass,1,0,0,blos,0,0.9682,NaN,NaN,4.0,-1345,0.9682,0.0,0,Sind,0.0,0.0417,0,1
4,84556,-977,NaN,NaN,NaN,N,Rest,NaN,0,2,NaN,NaN,NaN,225000.0,NaN,0,Unad,NaN,NaN,0,0,NaN,NaN,0,0,0.154565,0,0.0,0,0,Come,Hout,NaN,1,NaN,0.0,NaN,2,NaN,NaN,27558.0,5,1,NaN,Accs,NaN,0,Y,NaN,NaN,0,NaN,0,0.006629,NaN,0,NaN,180000.0,NaN,NaN,NaN,NaN,0,-2873.0,1,0,254700.0,Incr,NaN,F,-8486,0,0.0,0,NaN,0,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,-695.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MONY,0,NaN,NaN,0,0,1.0,0,NaN,NaN,Cass,1,0,0,NaN,0,NaN,NaN,NaN,NaN,-852,NaN,NaN,0,Sind,0.0,NaN,0,0

In [68]:
df.isnull().sum().sum()

7318445

In [69]:
df.shape

(246008, 122)

In [70]:
df.columns[df.isnull().any()]

Int64Index([  2,   3,   4,   7,  10,  11,  12,  13,  14,  16,  17,  18,  21,
             22,  25,  27,  32,  34,  35,  36,  38,  39,  40,  43,  44,  45,
             48,  49,  51,  54,  56,  58,  59,  60,  61,  68,  72,  74,  77,
             78,  79,  80,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
             92,  95,  96,  99, 101, 102, 107, 109, 110, 111, 112, 114, 115,
            118, 119],
           dtype='int64')

In [71]:
nulls=[]
for col in df.columns:
    if df[col].isnull().sum() > 30000:
        nulls.append(col)
print(nulls)

[2, 3, 4, 7, 10, 11, 12, 14, 17, 18, 21, 22, 32, 34, 36, 38, 39, 43, 44, 45, 48, 49, 51, 54, 56, 58, 59, 60, 61, 68, 74, 77, 78, 79, 80, 82, 83, 84, 86, 87, 88, 89, 90, 91, 92, 95, 96, 101, 102, 107, 109, 110, 111, 112, 114, 115, 119]

In [72]:
len(nulls)

57

In [73]:
df=df.drop(columns=nulls)

In [74]:
df.isna().sum()

0        0
1        0
5        0
6        0
8        0
      ...
116      0
117      0
118    811
120      0
121      0
Length: 65, dtype: int64

In [75]:
df.isna().sum().sum()

5038

In [76]:
df

,0,1,5,6,8,9,13,15,16,19,20,23,24,25,26,27,28,29,30,31,33,35,37,40,41,42,46,47,50,52,53,55,57,62,63,64,65,66,67,69,70,71,72,73,75,76,81,85,93,94,97,98,99,100,103,104,105,106,108,113,116,117,118,120,121
0,69769,-946,N,Bus2,0,2,180000.0,0,Unad,0,0,0,0,0.289573,0,0.0,0,0,Come,Hout,1,0.0,2,13189.5,10,1,0,N,0,0,0.008230,0,90000.0,0,-6378.0,1,0,227520.0,Hign,F,-12298,0,0.0,2,0,0,0,0.0,WEDY,0,0,0,4.0,0,Cass,1,0,0,0,-4670,0,Mard,0.0,0,0
1,236977,-92,Y,Othr,0,3,135000.0,0,Unad,0,0,0,0,0.514261,0,2.0,0,0,Come,Hout,1,2.0,3,13095.0,13,1,0,Y,1,0,0.003069,0,90000.0,0,-1292.0,1,0,161730.0,Secl,M,-15375,1,0.0,0,0,0,0,-509.0,TUEY,0,0,0,2.0,0,Cass,1,0,0,0,-1994,0,Mard,0.0,0,0
2,168821,-1646,N,Bus3,0,2,553500.0,0,Spor,0,1,0,0,0.486906,0,1.0,0,0,Worg,Hout,1,1.0,3,26307.0,5,1,0,Y,0,0,0.020713,0,135000.0,0,-7951.0,1,0,728847.0,Secl,M,-19307,0,0.0,0,0,0,0,-1474.0,TUEY,0,0,0,1.0,0,Cass,1,0,0,0,-2842,0,Sind,0.0,0,1
3,94708,-1651,N,Bus3,0,2,391500.0,0,Unad,0,1,0,0,0.675705,0,2.0,0,0,Come,Hout,1,2.0,2,34636.5,10,1,0,N,0,0,0.011703,0,135000.0,0,-1033.0,1,0,474183.0,Secl,M,-17791,0,0.0,0,0,0,0,-2016.0,TUEY,0,0,0,1.0,0,Cass,1,0,0,0,-1345,0,Sind,0.0,0,1
4,84556,-977,N,Rest,0,2,225000.0,0,Unad,0,0,0,0,0.154565,0,0.0,0,0,Come,Hout,1,0.0,2,27558.0,5,1,0,Y,0,0,0.006629,0,180000.0,0,-2873.0,1,0,254700.0,Incr,F,-8486,0,0.0,0,0,0,0,-695.0,MONY,0,0,0,1.0,0,Cass,1,0,0,0,-852,0,Sind,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246003,248161,-595,N,Bus3,0,2,405000.0,0,Unad,0,0,0,1,0.549668,0,1.0,0,0,Come,Hout,1,1.0,2,20250.0,14,1,0,Y,0,0,0.035792,0,135000.0,0,-6831.0,0,0,405000.0,Secl,F,-15374,0,0.0,1,0,0,0,-379.0,MONY,0,0,0,3.0,0,Revs,1,0,0,0,-4420,0,Mard,0.0,0,0
246004,257069,-4334,N,Mede,0,2,225000.0,0,Unad,0,0,0,0,0.569702,0,0.0,0,0,Stat,Hout,1,0.0,2,21528.0,8,1,0,N,0,0,0.018801,0,157500.0,0,-8490.0,1,0,272520.0,Secl,F,-19035,0,0.0,0,0,0,0,-374.0,MONY,0,0,0,1.0,0,Cass,1,0,0,0,-2561,0,Sind,0.0,0,0
246005,154350,365243,N,XNAA,0,2,234000.0,0,Unad,0,0,0,0,0.461966,0,1.0,0,1,Penr,Hout,1,1.0,2,24493.5,11,1,0,N,0,0,0.025164,0,90000.0,0,-8975.0,0,0,246357.0,Secl,F,-23088,0,0.0,0,0,0,0,-1689.0,SUNY,0,0,0,2.0,0,Cass,0,0,0,0,-4636,0,Cive,0.0,0,0
246006,148183,365243,N,XNAA,0,3,810000.0,0,Chin,0,1,0,0,0.459173,0,1.0,0,0,Penr,Hout,1,1.0,3,26901.0,9,1,0,Y,0,0,0.018209,0,112500.0,0,-10162.0,1,0,810000.0,Secl,F,-22148,0,0.0,0,0,0,0,-1329.0,WEDY,0,0,0,2.0,0,Cass,0,0,0,0,-4636,0,Mard,0.0,0,1
246007,5167,365243,Y,XNAA,0,2,877500.0,0,Famy,0,1,0,0,0.008171,0,9.0,0,0,Penr,Hout,1,9.0,2,27859.5,12,1,0,Y,0,0,0.018850,0,126000.0,0,-1487.0,1,0,1051245.0,Secl,F,-22079,0,0.0,0,0,0,0,-720.0,FRIY,0,0,0,2.0,0,Cass,0,0,0,0,-4266,0,Mard,0.0,0,0

In [77]:
df.dtypes

0        int64
1        int64
5       object
6       object
8        int64
        ...
116      int64
117     object
118    float64
120      int64
121      int64
Length: 65, dtype: object

In [78]:
df.isna().sum()

0        0
1        0
5        0
6        0
8        0
      ...
116      0
117      0
118    811
120      0
121      0
Length: 65, dtype: int64

In [79]:
df=df.rename(columns={0:'0',1:'1',5:'3',6:'4',8:'5',9:'6',13:'7',15:'8',16:'9',19:'10',20:'11',23:'12',24:'13',25:'14',26:'15',27:'16',28:'17',29:'18',30:'19',31:'20',33:'21',35:'22',37:'23',40:'24',41:'25',42:'26',46:'27',47:'28',50:'29',52:'30',53:'31',55:'32',57:'33',62:'34',63:'35',64:'36',65:'37',66:'38',67:'39',69:'40',70:'41',71:'42',72:'43',73:'44',75:'45',76:'46',81:'47',85:'48',93:'49',94:'50',97:'51',98:'52',99:'53',100:'54',103:'55',104:'56',105:'57',106:'58',108:'59',113:'60',116:'61',117:'62',118:'63',120:'64',121:'65'})

In [80]:
df.columns

Index(['0', '1', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
       '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25',
       '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37',
       '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49',
       '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61',
       '62', '63', '64', '65'],
      dtype='object')

In [81]:
# importing sweetviz
import sweetviz as sv
#analyzing the dataset
advert_report = sv.analyze(df)
#display the report
advert_report.show_html('Advertising.html')

c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\dataframe_report.py:74: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  all_source_names = [cur_name for cur_name, cur_series in source_df.iteritems()]
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\dataframe_report.py:109: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  filtered_series_names_in_source = [cur_name for cur_name, cur_series in source_df.iteritems()

                                             |          | [  0%]   00:00 -> (? left)

c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_numeric.py:25: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  stats["mad"] = series.mad()
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():
c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\sweetviz\series_analyzer_cat.py:28: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for item in category_counts.iteritems():

Report Advertising.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [82]:
from pandas_profiling import ProfileReport
prof = ProfileReport(df)
prof.to_file(output_file='output.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

c:\Users\beril\anaconda3\envs\pythonEnv\lib\site-packages\ydata_profiling\model\pandas\discretize_pandas.py:52: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  discretized_df.loc[:, column] = self._discretize_column(

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]